### ISSUE TITLE
Shortest path 

### ISSUE THREAD

**Issue by Shreya2704** [TheAlgorithms/C#487]
To find the shortest path between 2 cities

**Comment by sagnik-chatterjee** [comment]
Hi can i take up this issue ?
Plus any specific algortihm you have in mind ?

**Comment by sagnik-chatterjee** [comment]
hi @Shreya2704  can you verify if the issue is resolved ? I have done a pull request for this ...if you find this solves your problem kindly merge it or if further additions need to be made ,please list them here.

**Comment by deadshotsb** [comment]
@sagnik-chatterjee Well the Djikstra's algorithm can be used to find a single source shortest path, but as "To find the shortest path between 2 cities", I find it more like applying an all pair Shortest path (floyd warshall algorithm) You may consider adding a dynamic programming approach for that, you may refer to: https://www.geeksforgeeks.org/floyd-warshall-algorithm-dp-16/

**Comment by ManavpreetSingh** [comment]
Can i take this issue ? Let me know if you have any particular choice !

**Comment by plongueira** [comment]
Maybe use discrete mathematics theory for example directed graphs and weighted graphs have could solve the problem (i.e) the distance between 2 cities without a direct connection is unknown so in order to get a close reflect of the reality you could check different paths between those two cities,then adding the weights between each pair of cities from city source to destiny and that'd be all

**Comment by deadshotsb** [comment]
@ManavpreetSingh Yes sure

**Comment by HybridDog** [comment]
In practice, e.g. in a car navigation system, the graph is preprocessed so that the distance between two cities can later be queried in e.g. O(sqrt(n) log(n)), which is a lot faster than Dijkstra's algorithm (excluding the preprocessing time).
https://en.wikipedia.org/wiki/Contraction_hierarchies
